agents:
-   start: [8, 10]
    goal: [4, 6]
    name: cube1
-   start: [5, 4]
    goal: [5, 6]
    name: cube2
-   start: [1, 8]
    goal: [6, 6]
    name: cube3
-   start: [3, 10]
    goal: [7, 6]
    name: cube4
-   start: [7, 8]
    goal: [8, 6]
    name: cube5
-   start: [3, 5]
    goal: [9, 6]
    name: cube6
-   start: [7, 3]
    goal: [10, 6]
    name: cube7

map:
    dimensions: [12, 12]
